language: node_js
sudo: false
node_js:
  - node
  - lts/*
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: tlaziuk/rational-number
